import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components";
import ThemeProvider from "./theme-provider";
import AuthProvider from "./auth/session-provider";

const league_spartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={league_spartan.className}>
        <AuthProvider>
          <ThemeProvider>
            <div className="flex flex-col lg:min-h-screen lg:flex-row">
              <Navbar />
              <main>{children}</main>
            </div>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
